# Generated by Django 5.2.3 on 2025-06-24 07:45

import workflows.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_webhookendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='token',
            field=models.CharField(default=workflows.utils.generate_webhook_token, editable=False, max_length=64, unique=True),
        ),
    ]
