# Generated by Django 5.2.3 on 2025-06-25 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_executionlog_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='status',
            field=models.CharField(choices=[('TM', 'Trigger matched'), ('AE', 'Action enqueued'), ('AS', 'Action execution started'), ('AC', 'Action completed'), ('AF', 'Action failed'), ('RS', 'Retry scheduled'), ('RF', 'Retry failed'), ('IE', 'Internal error'), ('PP', 'Plugin Protocol error')], max_length=2),
        ),
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('user_config', models.JSONField()),
                ('path', models.FilePathField()),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_plugins', to='workflows.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'slug')},
            },
        ),
    ]
