# Generated by Django 5.2.3 on 2025-06-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_executionlog_status_installedplugin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstalledPlugin',
        ),
    ]
