# Generated by Django 5.2.3 on 2025-06-27 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_installedplugin_config_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedplugin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
