# Generated by Django 5.2.3 on 2025-06-29 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_action_created_by_trigger_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
    ]
