# Generated by Django 5.2.3 on 2025-06-24 06:44

import django.db.models.deletion
import uuid
import workflows.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=64)),
                ('token', models.CharField(default=workflows.utils.generate_token, max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workflows.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'platform')},
            },
        ),
    ]
