# Generated by Django 5.2.3 on 2025-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_remove_installedplugin_user_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedplugin',
            name='config_schema',
            field=models.JSONField(null=True),
        ),
    ]
