# Generated by Django 5.2.3 on 2025-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_alter_workspace_owner_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('read_workspace', 'Read Workspace'), ('update_workspace', 'Update Workspace'), ('delete_workspace', 'Delete Workspace'), ('read_workflow', 'Read Workflow'), ('update_workflow', 'Update Workflow'), ('delete_workflow', 'Delete Workflow'), ('create_workflow', 'Create Workflow'), ('read_trigger', 'Read Trigger'), ('update_trigger', 'Update Trigger'), ('delete_trigger', 'Delete Trigger'), ('create_trigger', 'Create Trigger'), ('read_action', 'Read Action'), ('update_action', 'Update Action'), ('delete_action', 'Delete Action'), ('create_action', 'Create Action'), ('read_ex_logs', 'Read Execution Logs'), ('read_webhook_endpoints', 'Read Webhook Endpoints'), ('write_webhook_endpoints', 'Write Webhook Endpoints'), ('read_installed_plugins', 'Read Installed Plugins'), ('update_installed_plugins', 'Update Installed Plugins'), ('delete_installed_plugins', 'Delete Installed Plugins'), ('create_installed_plugins', 'Create Installed Plugins')], max_length=100, unique=True),
        ),
    ]
