# Generated by Django 5.2.3 on 2025-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_remove_action_created_by_remove_trigger_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('read_workspace', 'Read Workspace'), ('update_workspace', 'Update Workspace'), ('delete_workspace', 'Delete Workspace'), ('read_workflow', 'Read Workflow'), ('update_workflow', 'Update Workflow'), ('delete_workflow', 'Delete Workflow'), ('create_workflow', 'Create Workflow'), ('read_wf_config', 'Read trigger/action of workflow'), ('update_wf_config', 'Update trigger/action of workflow'), ('delete_wf_config', 'Delete trigger/action of workflow'), ('create_wf_config', 'Create trigger/action of workflow'), ('read_ex_logs', 'Read Execution Logs'), ('read_webhook_endpoints', 'Read Webhook Endpoints'), ('write_webhook_endpoints', 'Write Webhook Endpoints'), ('read_installed_plugins', 'Read Installed Plugins'), ('update_installed_plugins', 'Update Installed Plugins'), ('delete_installed_plugins', 'Delete Installed Plugins'), ('create_installed_plugins', 'Create Installed Plugins')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], max_length=100, unique=True),
        ),
    ]
