# Generated by Django 5.2.3 on 2025-07-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('read_workspace', 'Read Workspace'), ('update_workspace', 'Update Workspace'), ('delete_workspace', 'Delete Workspace'), ('read_workflow', 'Read Workflow'), ('update_workflow', 'Update Workflow'), ('delete_workflow', 'Delete Workflow'), ('create_workflow', 'Create Workflow'), ('read_wf_config', 'Read trigger/action of workflow'), ('update_wf_config', 'Update trigger/action of workflow'), ('delete_wf_config', 'Delete trigger/action of workflow'), ('create_wf_config', 'Create trigger/action of workflow'), ('read_ex_logs', 'Read Execution Logs'), ('read_webhook_endpoints', 'Read Webhook Endpoints'), ('write_webhook_endpoints', 'Write Webhook Endpoints'), ('read_installed_plugins', 'Read Installed Plugins'), ('update_installed_plugins', 'Update Installed Plugins'), ('delete_installed_plugins', 'Delete Installed Plugins'), ('create_installed_plugins', 'Create Installed Plugins')], max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
